name: CI
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      jdk:
        default: 8
        type: string
      os:
        default: ubuntu-latest
        type: string
jobs:
  Test:
    name: Run tests
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ inputs.jdk }}
          distribution: temurin
      - name: Bump Guava version to 32.1.2-jre
        run: |
          mvn -s .github/maven-ci-settings.xml dependency:tree -D includes=com.google.* -B
          sed -i 's/30.1.1-jre/32.1.2-jre/' ~/.m2/repository/io/vertx/vertx-dependencies/5.0.0-SNAPSHOT/*.pom
          mvn -s .github/maven-ci-settings.xml dependency:tree -D includes=com.google.* -B          
      - name: Run tests
        run: mvn -s .github/maven-ci-settings.xml -q clean verify -B
